# Generated by Django 4.2.7 on 2024-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipients", "0002_alter_schoolrecipient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolrecipient",
            name="email_type",
            field=models.CharField(
                choices=[("GENERAL", "General report for principals"), ("LOST", "Lost mode report")],
                default="GENERAL",
                max_length=7,
            ),
        ),
    ]
