# Generated by Django 4.2.7 on 2024-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipients", "0003_schoolrecipient_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolrecipient",
            name="email_type",
            field=models.CharField(
                choices=[("GENERAL", "Receive general report"), ("LOST", "Receive lost mode report")],
                default="GENERAL",
                max_length=7,
            ),
        ),
    ]
