# Generated by Django 4.2.7 on 2024-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipients", "0004_alter_schoolrecipient_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolrecipient",
            name="school_name",
            field=models.CharField(
                choices=[
                    ("ADS", "Arizona Desert Elementary"),
                    ("CCS", "Cesar Chavez Elementary"),
                    ("DVS", "Desert View Elementary"),
                    ("EPS", "Ed Pastor Elementary"),
                    ("GES", "Gadsden Elementary School"),
                    ("RCS", "Rio Colorado Elementary"),
                    ("SLMS", "San Luis Middle School"),
                    ("SLPS", "San Luis Preschool"),
                    ("SWJH", "Southwest Junior High"),
                    ("DAC", "District Administrative Office"),
                    ("ALL", "All sites"),
                    ("TEST", "Test site"),
                ],
                default="ALL",
                max_length=4,
            ),
        ),
    ]
